### ISSUE TITLE
Server restart problem

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/vorbote#2]
Since we use the kafka topics itself as the events that clients can subscribe to, if we pass messages into a newly created topic, we need to restart the vorbote app to listen to the new topic - the app does not subscribe to newly created topics automatically - we could lose messages in the process of restart though

**Comment by vikasrohit** [comment]
Sorry to jump @cwdcwd  in but may be we can expose rest endpoints to register new topics to the system which can immediately start listening for new topics and when anyhow the app is restarted it would automatically register all topics.

**Comment by cwdcwd** [comment]
@callmekatootie this one still an issue?

**Comment by callmekatootie** [comment]
We may not lose messages any more during restarts since we now fetch old messages too but we will not get new topics - for that a restart is a must.

I am 99% sure that is the case but I will test it out and confirm that this is true

**Comment by cwdcwd** [comment]
thanks

**Comment by callmekatootie** [comment]
Checked this out. Kindly ignore my earlier message. I confused Lauscher and Vorbote.

So, the original issue still exists - if a new topic is added, while the server is already active, we are not notifying any webhook created for the new topic. We have to restart the server to listen to new topic

**Comment by callmekatootie** [comment]
I do see in the logs that it is able to determine that a new topic exists, but I am guessing it does not subscribe to it
