### ISSUE TITLE
Webhook confirmation not working

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/vorbote#42]
On the webhook creation page, there's this message:

> When you create this Resthook, it will immediately send a POST request to the endpoint specified. There will be no request body. Instead, there will be a custom header named x-hook-secret. To this request, your endpoint needs to respond with a JSON object having an attribute x-hook-secret for which the value is the value that was passed in the header mentioned earlier.

The problem I see is that this line:  https://github.com/topcoder-platform/vorbote/blob/145351da71f5a86dc03c1e0bee2c9c0e1c21ae08/src/services/RestHookService.js#L89  *is* sending a body - it's `{}`, but not *technically* no request body.  If we replace that with an empty string, like `''`, *then* it's considered an empty body.

This was causing problems with lambda webhook validation.

**Comment by callmekatootie** [comment]
Thank you for fixing this! Changes are now merged.
