### ISSUE TITLE
Userdefined, sandboxed JS functions for determining if hook should fire

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/vorbote#9]
Expand the current system to do the following:
- allow for a user to enter an arbitrary piece of JS code 
- JS code takes in only the event payload
- JS code returns on a boolean value
- JS code executes when subscribed event comes in 
- if code returns true then fire webhook
- if code returns false then ignore event

The purpose of this is enhancement is to allow the user to determine what events they're interested in and clamp down the "firehose" of all topics

**Comment by cwdcwd** [comment]
@callmekatootie what do you think about this one?

**Comment by callmekatootie** [comment]
I am not sure if this will scale well. If we have many users listening, they will be executing the js code on our server... I can get this in, but I am of the opinion that this type of filtering is best left to the subscriber and not to vorbote...

**Comment by cwdcwd** [comment]
let's find out =)
we can always find ways to scale. worst case we pull it out.

**Comment by callmekatootie** [comment]
Ok. Any limitations on the size of the code? Is it allowed to make third party api calls? I realize that we are thinking simple here but the user may not :)

**Comment by cwdcwd** [comment]
That crossed my mind as well. Let's leave it pretty open to start and limit to just number of lines/bytes in size. Right now we're only allowing admins & CPs to use the service so we're in a controlled release. 
Perhaps we work up to something like [this](https://blog.risingstack.com/writing-a-javascript-framework-sandboxed-code-evaluation/) at some point or we limit what user types can use JS in their hooks

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JS event publishing gate](https://trello.com/c/0WEHhPPi/9-js-event-publishing-gate)

**Comment by callmekatootie** [comment]
This one is fixed and can be closed

**Comment by cwdcwd** [comment]
this one looks great. May want to expand upon it but we'll open new tickets for that
